export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';
export const LOAD_CHATS_SUCCESS = 'LOAD_CHATS_SUCESS';
export const LOAD_CHATS_ERROR = 'LOAD_CHATS_ERROR';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';
export const CHANGE_INPUT_VAL = 'CHANGE_INPUT_VAL';
export const CLEAR_INPUT_VAL = 'CLEAR_INPUT_VAL';